### ISSUE TITLE
Dialog boxes do not appear for the updated package

### ISSUE THREAD

**Issue by supratim1121992** [SciViews/svDialogs#3] opened 2018-07-03 07:29 UTC
I am using R(3.4.4) along with RStudio (1.1.453). The updated version of the package (1.0.0) does not result in dialog boxes appearing for the lists (created using `dlgList()`).
The previous version of the `svDialogs` package (0.9-57) however still works fine.

**Comment by phgrosjean** [comment] 2018-07-03 08:29
Hello,

Could you give more informations about your system, please? (OS, R packages loaded, …), and also a small reproductive example of your problem?
Best,

Philippe Grosjean

**Comment by supratim1121992** [comment] 2018-07-03 08:52
I am using Windows 10. I am using your package to develop a UI based analysis module. Before the package got updated, I had dialog boxes appearing for the lists i had created. However, after the package got updated, the dialog boxes stopped appearing and what I get is something like this printed on the console to make a selection.

Outlier detection - Select one or 0 to cancel 

1: Detect outliers using standard deviation (6 sigma)
2: Detect outliers using Interquartile range (IQR)

Moreover, the messages have lost the indentation I had used with the previous version of the package.

If you want, you can even use the package I created and check. The following code should give you an idea of what has been happening.

library(devtools)
install_github("supratim1121992/AutoAnalyse")
library(AutoAnalyse)

data("Titanic")
dt_proc<-Pre_Proc(dataset = Titanic)
Auto_EDA(dataset = dt_proc)

I have to remove the current version of `svDialogs` and install the previous version (0.9-57) to be able to work with it as before.

**Comment by phgrosjean** [comment] 2018-07-03 09:27
Support for RStudio was introduced in version 1.0.0 of svDialogs. It works as follows:

- If a graphical dialog box exists, use it,
- If it does not exists, or the context could be problematic, fall back to a textual version at the R console.

This depends on the dialog box. For instance, there are always graphical message boxes, or input boxes available in RStudio, but no built-in list dialog boxes.

So the code checks if it is RStudio Desktop or Server. If it is Desktop, it uses the standard graphical list dialog box. If it is the Server version, there is no guarantee that the graphical dialog box will be available, and if it is, it may appear on the *server*, not on the client’s computer. So, we fall back to the textual version.

So, unless my code to detect the RStudio version is incorrect, I deduce that you use RStudio Server (is it?), and in this case, svDialogs behaves as expected, see ?dlgList.

Best,

Philippe Grosjean

**Comment by supratim1121992** [comment] 2018-07-03 10:07
I'm using RStudio Desktop and like I said I don't have this issue with the previous version of your package. Only the version 1.0.0 causes this issue. If I use 

`remove.packages("svDialogs")`

and reinstall v0.9-57 (from .tar file), everything works fine.

**Comment by phgrosjean** [comment] 2018-07-05 14:49
> On 3 Jul 2018, at 12:07, Supratim Chaudhuri <notifications@github.com> wrote:
> 
> I'm using RStudio Desktop and like I said I don't have this issue with the previous version of your package.
> 
OK, I will lok at this, but for now, I am at a conference.
Best,

Phiippe Grosjean

**Comment by supratim1121992** [comment] 2018-07-11 06:06
Hi Philippe

Did you get a chance to inspect the issue?

**Comment by phgrosjean** [comment] 2018-07-12 11:27
Could you try with the latest devel version? I think it solves your problem. In case you don't want to compile from source, you can get Windows binaries here: https://ci.appveyor.com/api/buildjobs/55iqs8g95xmhk9ms/artifacts/svDialogs_1.0.1.zip

**Comment by supratim1121992** [comment] 2018-07-12 11:51
Thanks Philippe for getting back to me. The dlgList function works as expected with version 1.0.1. However, the messages don't show proper indentation. For instance, if I want two messages printed in separate lines I'm using 
`dlgMessage(message = c("message1","message2"),type = "ok"`
But that does not introduce a line break. Should I use '\n' instead?

**Comment by phgrosjean** [comment] 2018-07-12 12:15
That is another issue. I can confirm this under RStudio. However, the dlgMessage() code includes '\n' as expected, but the RStudio message box does not honor it. It is a limitation, apparently, with RStudio message box, and can do nothing in svDialogs to solve this. This is now specified in ?dlgMessage
Since the initial problem seems to be solved, I close the issue.

**Closed as completed by phgrosjean** 2018-07-12 12:15 UTC

**Comment by supratim1121992** [comment] 2018-07-12 12:23
OK thank you for that.
